
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahpmmgnkksrbpthniptg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocG1tZ25ra3NyYnB0aG5pcHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjYyMjYsImV4cCI6MjA1NTk0MjIyNn0.tnI6lc4uDlfDIyF7plIAzK60jEkn8wKEDH1MSAaW29o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper for getting the current workspace ID
export const getCurrentWorkspaceId = async (): Promise<string | null> => {
  try {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session?.user?.id) return null;
    
    const { data: profile } = await supabase
      .from('profiles')
      .select('current_workspace_id')
      .eq('id', session.user.id)
      .single();
    
    return profile?.current_workspace_id || null;
  } catch (error) {
    console.error('Error getting current workspace:', error);
    return null;
  }
};

// Helper for database operations that need the workspace context
export const withWorkspace = async <T>(
  callback: (workspaceId: string) => Promise<T>
): Promise<T | null> => {
  const workspaceId = await getCurrentWorkspaceId();
  if (!workspaceId) {
    console.error('No workspace found');
    return null;
  }
  return callback(workspaceId);
};
