// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Using your actual Supabase project
const SUPABASE_URL = "https://ahpmmgnkksrbpthniptg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
// Expose Supabase client to browser console
;(window as any).supabase = supabase;

// Helper for getting the current workspace ID
export const getCurrentWorkspaceId = async (): Promise<string | null> => {
  try {
    console.log("🔑 Getting current workspace ID");
    const {
      data: { session },
      error: authError,
    } = await supabase.auth.getSession();

    if (authError) {
      console.error("❌ Auth error getting session:", authError);
      return null;
    }

    if (!session?.user?.id) {
      console.warn("⚠️ No user session available");
      return null;
    }

    console.log("👤 User authenticated with ID:", session.user.id);

    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("current_workspace_id")
      .eq("id", session.user.id)
      .single();

    if (profileError) {
      console.error("❌ Error fetching user profile:", profileError);
      return null;
    }

    if (!profile?.current_workspace_id) {
      console.warn("⚠️ No workspace ID found in user profile");
      return null;
    }

    console.log("🏢 Found workspace ID:", profile.current_workspace_id);
    return profile.current_workspace_id;
  } catch (error) {
    console.error("❌ Error getting current workspace:", error);
    return null;
  }
};

// Helper for database operations that need the workspace context
export const withWorkspace = async <T>(
  callback: (workspaceId: string) => Promise<T>,
): Promise<T | null> => {
  const workspaceId = await getCurrentWorkspaceId();
  if (!workspaceId) {
    console.error("No workspace found");
    return null;
  }
  return callback(workspaceId);
};
